name: Tests

on:
  push:
    branches:
      - dev
      - main

jobs:
  unit-test:
    runs-on: ubuntu-20.04

    container:
      image: epitechcontent/epitest-docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run unit tests
        run: |
          mkdir -p artifacts
          make tests_run > artifacts/unit_tests_output.txt

      - name: Run coverage
        run: |
          make coverage > artifacts/coverage_output.txt

      - name: Upload coverage outputs
        uses: actions/upload-artifact@v3
        with:
          name: coverage_outputs
          path: artifacts/
        if: always()